apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidcClientSecretName }}
  namespace: {{ .Values.pinnipedNamespace }}
type: secrets.pinniped.dev/oidc-client
stringData:
  clientID: {{ .Values.oidcClientId | quote }}
  clientSecret: {{ .Values.oidcClientSecret | quote }}
