server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  gzip off;
  location = / {
    try_files /index.html =404;
  }
  location = /kubeconfig.yaml {
    alias /data/kubeconfig;
    default_type application/yaml;
    add_header Content-Disposition 'attachment; filename="{{ .Values.loginUi.clusterDomain }}.yaml"';
    add_header Cache-Control 'no-store';
  }
  location / {
    return 404;
  }
}
